name: trina_grid
description: A data grid that can be controlled by the keyboard on desktop and web. Of course, it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table, Sticky)
version: 1.5.0
repository: https://github.com/doonfrs/trina_grid

environment:
  sdk: ^3.7.0

# This allows the package to be run as an executable
executables:
  trina_grid: trina_grid

dependencies:
  flutter:
    sdk: flutter
  # Follows the intl version included in Flutter.
  # https://github.com/flutter/flutter/blob/84a1e904f44f9b0e9c4510138010edcc653163f8/packages/flutter_localizations/pubspec.yaml#L11
  intl: any
  rxdart: ^0.28.0
  collection: ^1.18.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
